# Generated by Django 6.1 on 2026-08-12 17:32

import books.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(upload_to='books/covers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), books.models.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='book',
            name='digital_file',
            field=models.FileField(blank=True, null=True, upload_to='books/files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'epub']), books.models.validate_file_size]),
        ),
    ]
