# Generated by Django 6.1 on 2026-08-09 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0002_alter_author_options_alter_book_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'درحال بررسی'), ('processing', 'درحال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=10, verbose_name='Status')),
                ('payment_status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده'), ('failed', 'ناموفق')], default='unpaid', max_length=6, verbose_name='Payment Status')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Total Price')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='Province')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal Code')),
                ('address', models.CharField(blank=True, max_length=700, null=True, verbose_name='Address')),
                ('order_notes', models.CharField(blank=True, max_length=700, null=True, verbose_name='Order Notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='books.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
